openapi: 3.0.0
info:
  title: AdAnalytics API
  description: API para análise de métricas de anúncios do Facebook e Google
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Servidor de desenvolvimento

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    RegisterRequest:
      type: object
      required:
        - email
        - password
        - name
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        name:
          type: string

    UpdateUserRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string

    UpdateUserSettingsRequest:
      type: object
      properties:
        settings:
          type: object

    MetricsResponse:
      type: object
      properties:
        value:
          type: number
        trend:
          type: number
        data:
          type: array
          items:
            type: object

paths:
  /auth/login:
    post:
      tags:
        - Autenticação
      summary: Login de usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Credenciais inválidas

  /auth/register:
    post:
      tags:
        - Autenticação
      summary: Registro de novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Usuário registrado com sucesso
        '400':
          description: Dados inválidos

  /user/list:
    get:
      tags:
        - Usuários
      summary: Lista todos os usuários
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Lista de usuários retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /user/{id}:
    get:
      tags:
        - Usuários
      summary: Obtém um usuário específico
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuário encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Usuário não encontrado

  /user:
    put:
      tags:
        - Usuários
      summary: Atualiza dados do usuário
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: Usuário atualizado com sucesso
        '400':
          description: Dados inválidos

  /user/settings:
    put:
      tags:
        - Usuários
      summary: Atualiza configurações do usuário
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserSettingsRequest'
      responses:
        '200':
          description: Configurações atualizadas com sucesso
        '400':
          description: Dados inválidos

  /metrics/facebook/roi:
    get:
      tags:
        - Métricas Facebook
      summary: Obtém ROI dos anúncios do Facebook
      security:
        - BearerAuth: []
      responses:
        '200':
          description: ROI calculado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsResponse'

  /metrics/google/roi:
    get:
      tags:
        - Métricas Google
      summary: Obtém ROI dos anúncios do Google
      security:
        - BearerAuth: []
      responses:
        '200':
          description: ROI calculado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsResponse'

  /metrics/facebook/cpa:
    get:
      tags:
        - Métricas Facebook
      summary: Obtém CPA dos anúncios do Facebook
      security:
        - BearerAuth: []
      responses:
        '200':
          description: CPA calculado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsResponse'

  /metrics/google/cpa:
    get:
      tags:
        - Métricas Google
      summary: Obtém CPA dos anúncios do Google
      security:
        - BearerAuth: []
      responses:
        '200':
          description: CPA calculado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsResponse'

  /metrics/facebook/cpc:
    get:
      tags:
        - Métricas Facebook
      summary: Obtém CPC dos anúncios do Facebook
      security:
        - BearerAuth: []
      responses:
        '200':
          description: CPC calculado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsResponse'

  /metrics/google/cpc:
    get:
      tags:
        - Métricas Google
      summary: Obtém CPC dos anúncios do Google
      security:
        - BearerAuth: []
      responses:
        '200':
          description: CPC calculado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsResponse'

  /metrics/facebook/ctr:
    get:
      tags:
        - Métricas Facebook
      summary: Obtém CTR dos anúncios do Facebook
      security:
        - BearerAuth: []
      responses:
        '200':
          description: CTR calculado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsResponse'

  /metrics/google/ctr:
    get:
      tags:
        - Métricas Google
      summary: Obtém CTR dos anúncios do Google
      security:
        - BearerAuth: []
      responses:
        '200':
          description: CTR calculado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsResponse'

  /metrics/facebook/roas:
    get:
      tags:
        - Métricas Facebook
      summary: Obtém ROAS dos anúncios do Facebook
      security:
        - BearerAuth: []
      responses:
        '200':
          description: ROAS calculado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsResponse'

  /metrics/google/roas:
    get:
      tags:
        - Métricas Google
      summary: Obtém ROAS dos anúncios do Google
      security:
        - BearerAuth: []
      responses:
        '200':
          description: ROAS calculado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsResponse'

  /chat:
    post:
      tags:
        - Chat
      summary: Endpoint para interação com chat GPT-4
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: Resposta do chat gerada com sucesso
        '400':
          description: Requisição inválida